practice_name: "Swift Auto Care"
voice: "Polly.Brian"
language: "en-GB"

openings:
  - "Hi, Swift Auto Care — how can I help today?"
  - "Hello, Swift Auto Care. What can I do for you?"
  - "Swift Auto Care, you're through to the reception. How can I help?"

backchannels:
  - "Okay, that’s fine."
  - "Yeah, sure."
  - "Hmm, okay."
  - "Right, I understand."
  - "No problem."
  - "Alright."
  - "Got it."
  - "Makes sense."
  - "Absolutely."
  - "Sure thing."
  - "Okay, noted."
  - "All good."

closings:
  - "Okay, thanks for calling Swift Auto Care. Goodbye."
  - "Alright, appreciate the call. Goodbye."
  - "Thanks for calling. Take care, goodbye."

hours: "We’re open Monday to Friday eight to six, Saturday nine to two. Closed Sundays and bank holidays."
address: "Unit 3, Trade Park, Oakford, OX1 3CD. Entrance by the grey shutter."
prices:
  mot: "MOT is fifty-five pounds."
  service_minor: "Minor service starts at one hundred and twenty pounds."
  service_major: "Major service starts at two hundred and thirty pounds."
  diagnostics: "Diagnostics is sixty pounds."
  tyres: "Tyres vary by size — we can quote once we know your vehicle."
  brakes: "Brake pads and discs vary; we’ll quote after a quick check."

consent_lines:
  - "By providing your number, you agree to receive booking confirmations and reminders."
  - "We won’t spam you — just essential updates about your appointment."
