practice_name: "Oak Dental"
voice: "Polly.Amy"
language: "en-GB"

openings:
  - "Hi, Oak Dental. How can I help today?"
  - "Hello, Oak Dental speaking — how can I help?"
  - "Hi there, Oak Dental — what do you need today?"
  - "Oak Dental here. How can I help you?"
  - "Thanks for calling Oak Dental. What can I do for you?"

backchannels:
  - "Okay, that's fine."
  - "Yeah, sure."
  - "Hmm, okay."
  - "Right, I understand."
  - "No problem."
  - "Alright."
  - "Got it."
  - "Makes sense."
  - "Absolutely."
  - "Sure thing."
  - "Okay, noted."
  - "All good."
  - "Sounds good."
  - "Okay, let me check."
  - "One moment."
  - "Alright, give me a sec."
  - "Great, thanks."
  - "Lovely, thanks."

thinking_fillers:
  - "Okay, one moment while I check."
  - "Alright, let me have a quick look."
  - "No worries, give me a second."
  - "Right, I'm checking that now."
  - "Okay, let's see what we've got."
  - "Sure, I’m pulling that up."

clarifiers:
  - "Sorry, could you repeat that in a few words?"
  - "I didn’t quite catch that — was that a booking, our hours, or prices?"
  - "One more time please — which day did you want?"
  - "Could you say that slowly for me?"

closings:
  - "Okay, thanks for calling. Have a lovely day. Goodbye."
  - "Alright, appreciate the call. Take care — goodbye."
  - "Thanks for calling Oak Dental. Bye for now."

hours: "We're open Monday to Friday nine to five, Saturday nine to one. Closed Sundays and bank holidays."
address: "We're at 12 High Street, Oakford, OX1 2AB. Entrance next to the pharmacy."
prices: "A routine check-up is forty five pounds. Hygiene is sixty five. Whitening starts from two hundred and fifty."

services:
  checkup: "Check-up is £45"
  hygiene: "Hygiene is £65"
  whitening: "Whitening starts from £250"
  extraction: "Tooth extraction is £120"
