practice_name: "Oak Dental"
voice: "Polly.Amy"
language: "en-GB"
openings:
  - "Hiya, thanks for calling Oak Dental - how can I help today?"
  - "Hello, you've reached Oak Dental. What can I do for you?"
  - "Good to hear from you at Oak Dental. How can I help?"
  - "Oak Dental speaking - how can I help today?"
  - "Thanks for calling Oak Dental. Would you like our hours, prices, or to make a booking?"
backchannels:
  - "Okay, that's fine."
  - "Yeah, sure."
  - "Hmm, okay."
  - "Right, I understand."
  - "No problem."
  - "Alright."
  - "Got it."
  - "Makes sense."
  - "Absolutely."
  - "Sure thing."
  - "Okay, noted."
  - "All good."
  - "Okay, sure."
  - "Sounds good."
  - "No worries."
  - "Alright, let me check."
  - "Okay, one second."
  - "Right, let's see here."
  - "Yep, I can help with that."
  - "Okay, I hear you."
  - "Great, thanks."
  - "Lovely, thanks."
thinking_fillers:
  - "Okay, one moment."
  - "Alright, let me just check."
  - "No worries, give me a second."
  - "Okay, let's see what we've got."
  - "Sure, let me pull that up."
  - "Right, I'm checking that now."
  - "Okay, just a sec."
  - "Alright, I'll take a quick look."
clarifiers:
  - "Sorry, could you say that again in a few words?"
  - "I didn't quite catch that - did you mean a booking, our hours, or prices?"
  - "One more time please - which day would you like?"
  - "Could you repeat that slowly for me?"
closings:
  - "Okay, thanks for calling - have a lovely day. Goodbye."
  - "Alright, appreciate the call. Take care, goodbye."
  - "Thanks for calling. Have a great day. Goodbye."
  - "Cheers for calling. Bye for now."
hours: "We're open Monday to Friday nine to five, Saturday nine to one. Closed Sundays and bank holidays."
address: "We're at 12 High Street, Oakford, OX1 2AB. Entrance next to the pharmacy."
prices: "A routine check-up is forty five pounds. Hygiene is sixty five. Whitening starts from two hundred and fifty."
