practice_name: "Oak Dental"
voice: "Polly.Amy"
language: "en-GB"
hours: "We’re open Monday to Friday nine to five; Saturday ten to one; Sundays and bank holidays closed."
address: "12 High Street, Oakford, OX1 2AB."
prices: "Check-up forty five pounds, hygiene sixty five, whitening from two hundred and fifty."
openings:
  - "Hiya, thanks for calling Oak Dental — how can I help today?"
  - "Hello, you’ve reached Oak Dental. What can I do for you?"
  - "Good to hear from you at Oak Dental. How can I help?"
  - "Oak Dental speaking — how can I help today?"
  - "Thanks for calling Oak Dental. Would you like our hours, prices, or to make a booking?"
