practice_name: "Oak Dental"
voice: "Polly.Amy"
language: "en-GB"
hours: "We’re open Monday to Friday nine to five; Saturday ten to one; Sundays and bank holidays closed."
address: "12 High Street, Oakford, OX1 2AB."
prices: "Check-up forty five pounds, hygiene sixty five, whitening from two hundred and fifty."
