# Map inbound 'To' numbers to a practice profile and friendly name.
# Replace these placeholders with your real Twilio numbers after this PR:
tenants:
  "+441111111111":
    profile: dental
    practice_name: "Oak Dental"
  "+442222222222":
    profile: mechanic
    practice_name: "Swift Auto Care"
